server:
  #尝试http2和https
  http2.enabled: true
  #https端口
  port: 8443
  http-port: 8899
  context-path: "/kite"
  ssl:
    key-store: "classpath:private_key.p12"
    key-store-password: "000000"
    #keyStoreType: "PKCS12" #默认标准
  undertow:
    worker-threads: 200
    accesslog:
      enabled: true
      dir: logs
      pattern: "[%{time,yyyy-MM-dd HH:mm:ss.S z}] %{s,name} %{i,X-Forwarded-For} %a \"%r\" %s (%D ms)"
      prefix: access_log.
      rotate: true
      suffix: log

logging:
  level:
    root: "INFO"
    io.waves.cloud.kitemanager.websocket.KiteWebSocketEndpoint: "DEBUG"
    io.waves.cloud.kitemanager.framework.ControllerHelper: "DEBUG"

spring:
  application:
    name: "kite-manager"
  #h2 database console
  h2.console:
    enabled: true
    path: /mm-h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:file:./db/kitemanager"
    username: "yt"
    password: "yt"
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    validation-query: "SELECT 1 FROM DUAL"
    time-between-eviction-runs-millis: 10000
    min-evictable-idle-time-millis: 10000
    max-evictable-idle-time-millis: 30000
    initial-size: 5
    max-active: 200
    max-wait: 60000
    min-idle: 1

mybatis.config-location: classpath:mybatis-config.xml

management:
  port: 18899
  context-path: "/admin"
  security:
    enabled: false

#kite mangager custom setting
kitemanager:
  # is enable AuthInterceptor
  authEnabled: true
  openApiApp:
    # the open api timestamp timeout interval seconds
    tokenInterval: 30
  maxClientNumber: 20000
  # kite agent connection auth setting
  connectionAuthEnabled: false
  connectionSecret: hellokitemanager