server:
  #尝试http2和https
  http2.enabled: true
  #https端口
  port: 8443
  http-port: 8899
  ssl:
    key-store: "classpath:undertow.jks"
    key-store-password: "000000"
    #keyStoreType: "PKCS12" #默认标准
  undertow:
    worker-threads: 200
    accesslog:
      enabled: true
      dir: logs
      pattern: "%t %a \"%r\" %s (%D ms)"
      prefix: access_log
      rotate: true
      suffix: .log

logging:
  level:
    root: "INFO"

spring:
  application:
    name: "kitemanager"

management:
  port: 18899
  context-path: "/admin"
  security:
    enabled: false