server:
  #尝试http2和https
  http2.enabled: true
  #https端口
  port: 8443
  http-port: 8899
  context-path: "/kite"
  ssl:
    key-store: "classpath:private_key.p12"
    key-store-password: "000000"
    #keyStoreType: "PKCS12" #默认标准
  undertow:
    worker-threads: 200
    accesslog:
      enabled: true
      dir: logs
      pattern: "[%{time,yyyy-MM-dd HH:mm:ss.S z}] %{i,X-Forwarded-For} %a \"%r\" %s (%D ms)"
      prefix: access_log
      rotate: true
      suffix: .log

logging:
  level:
    root: "INFO"
    io.waves.cloud.kitemanager.websocket.KiteWebSocketEndpoint: "DEBUG"
    io.waves.cloud.kitemanager.framework.ControllerHelper: "DEBUG"

spring:
  application:
    name: "kite-manager"

management:
  port: 18899
  context-path: "/admin"
  security:
    enabled: false